name: Refresh Snapshot

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate snapshot
        run: node scripts/fetch-stars.js
        env:
          GITHUB_TOKEN: ${{ secrets.LLM_STARS_PAT }}
          HOT_TOPICS: "llm,agent,rag,tts,voice"
          WINDOW_DAYS: 30
          MIN_STARS: 50
      - name: Commit & push
        run: |
          if git diff --quiet; then
            echo "No changes";
          else
            git config user.name "snapshot-bot"
            git config user.email "actions@users.noreply.github.com"
            git add data/latest.json data/snapshots/*.json
            git commit -m "chore: refresh snapshot $(date -u +%Y-%m-%dT%H:%MZ)"
            git push
          fi
